### ISSUE TITLE
新添加的mysql数据库一直连接不成功

### ISSUE THREAD

**Issue by 15201530233** [framely/framely#4]
![image](https://user-images.githubusercontent.com/53588569/87633769-90545f80-c76e-11ea-9c2f-a61808322a24.png)

**Comment by xiaoyunwu** [comment]
where is the 60.205.190.231?

**Comment by xiaoyunwu** [comment]
I think we should remove the connection from platform, and if we need to
have some operational information for hosting, we need to do it somewhere
else.  @lu

Xiaoyun

**Comment by 15201530233** [comment]
这个地址是当时kuijuan给我的，可以连接老dev，里边有老dev机器人MySQL的数据

数据库连接：
Name:ni-dev
Host:60.205.190.231
Username:ni_dev
Password:NI_dev007
Port:40008
